# Generated by Django 2.2 on 2019-04-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('age_month', models.IntegerField(default=0)),
                ('age_year', models.BigIntegerField(db_index=True, default=0)),
                ('breed', models.CharField(db_index=True, max_length=500, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', models.CharField(db_index=True, max_length=250, null=True)),
                ('story', models.TextField(help_text='Write a story about the pet', null=True)),
                ('sterilized', models.BooleanField(db_index=True, default=False)),
                ('house_trained', models.BooleanField(db_index=True, default=False)),
                ('is_adopted', models.BooleanField(db_index=True, default=False)),
                ('show_badge', models.BooleanField(default=False)),
                ('characteristics', models.TextField(db_index=True, help_text='Specify pet traits such as - Curious, Handsome, Playful, Loves Treats, Clever, Gold eyes, Medium length fur', null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=50)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=250)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('G', 'General'), ('A', 'Adoption')], db_index=True, default='G', max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('query', models.TextField(null=True)),
                ('location', models.CharField(db_index=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=100)),
                ('pet_name', models.CharField(max_length=100, null=True)),
                ('is_adopted', models.BooleanField(default=False)),
                ('pet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.Detail')),
            ],
        ),
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
