# Generated by Django 2.2 on 2019-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20190420_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
