# Generated by Django 2.2 on 2019-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20190421_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='added_by',
            field=models.CharField(default='Sumit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='email',
            field=models.CharField(default='dugar.sumit1990@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='mobile',
            field=models.CharField(default='+4915258398560', max_length=15),
            preserve_default=False,
        ),
    ]
