# Generated by Django 2.2 on 2019-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20190421_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='peepalfarm_approved',
            field=models.BooleanField(default=False),
        ),
    ]
