# Generated by Django 2.2 on 2019-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_detail_peepalfarm_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='location',
        ),
        migrations.AddField(
            model_name='detail',
            name='city',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='country',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='state',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
