# Generated by Django 2.2 on 2019-05-05 10:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20190427_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
