# Generated by Django 2.2 on 2019-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20190505_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='city',
        ),
    ]
