# Generated by Django 2.2 on 2019-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_remove_detail_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='state',
        ),
        migrations.AddField(
            model_name='detail',
            name='city',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
