# Generated by Django 2.2 on 2019-05-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20190505_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
