# Generated by Django 2.2 on 2019-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20190505_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
