# Generated by Django 2.2 on 2019-05-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_auto_20190525_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='age',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
