# Generated by Django 2.2 on 2019-05-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20190525_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='cat_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='dog_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='hair_length',
            field=models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], default='Medium', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='kid_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='size',
            field=models.CharField(choices=[('Small', 'Small (1-10kg)'), ('Medium', 'Medium (10-20kg)'), ('Large', 'Large (20-30kg)'), ('X-Large', 'X-Large (30+ kg)')], default='Medium', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail',
            name='characteristics',
            field=models.TextField(db_index=True, help_text='Specify pet traits such as - Curious, Handsome, Playful, Loves Treats, Clever, Gold eyes.', null=True),
        ),
    ]
