# Generated by Django 2.2 on 2019-08-24 11:27

import django.contrib.postgres.fields
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_auto_20190525_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='forbidden_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_countries.fields.CountryField(max_length=2, null=True), db_index=True, default=list, help_text='Specify countries in which adoptions of this pet is not allowed.', size=None),
        ),
    ]
